services:
   db:
     image: mysql:8
     volumes:
       - ./data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: fastladder
       MYSQL_DATABASE: fastladder
       MYSQL_USER: fastladder
       MYSQL_PASSWORD: fastladder1234
   web:
     image: yakumosaki/fastladder:latest
     env_file: env.production
     ports:
       - "5000:5000"
     depends_on:
       - db
     restart: always
   crawler:
     image: yakumosaki/fastladder:latest
     env_file: env.production
     command: bash -c "bundle exec ruby script/crawler"
     depends_on:
       - db
     restart: always

